### ISSUE TITLE
File Provisioner - relative upload paths result in kernal panic

### ISSUE THREAD

**Issue by mefellows** [packer-community/packer-windows-plugins#13]
When attempting the use of a relative upload path on a packer provisioning run, I get a kernel panic. An example configuration for the provisioner:

```
 {
  "type": "file",
  "source": "./DSC",
  "destination": "C:/Windows/Temp/DSC"
},

```

See following log output for detail:

```
mfellows@matt.mit ~/development/dius/hackathong3-packer $ PACKER_LOG=true PACKER_LOG_PATH=./packer.log packer build -only=virtualbox-windows-ovf ./winrm-community.json
virtualbox-windows-ovf output will be in this color.

==> virtualbox-windows-ovf: Starting HTTP server on port 8887
==> virtualbox-windows-ovf: Importing VM: /Users/mfellows/Downloads/output-virtualbox-iso/packer-virtualbox-iso-1417096689.ovf
==> virtualbox-windows-ovf: Creating forwarded port mapping for WinRM (host port 5822)
==> virtualbox-windows-ovf: Executing custom VBoxManage commands...
    virtualbox-windows-ovf: Executing: modifyvm packer-virtualbox-windows-ovf-1420540507 --memory 2048
    virtualbox-windows-ovf: Executing: modifyvm packer-virtualbox-windows-ovf-1420540507 --vram 64
    virtualbox-windows-ovf: Executing: modifyvm packer-virtualbox-windows-ovf-1420540507 --cpus 2
==> virtualbox-windows-ovf: Starting the virtual machine...
==> virtualbox-windows-ovf: Waiting 30s for boot...
==> virtualbox-windows-ovf: Typing the boot command...
==> virtualbox-windows-ovf: Waiting for WinRM to become available...
==> virtualbox-windows-ovf: Connected to WinRM!
==> virtualbox-windows-ovf: Uploading VirtualBox version info (4.3.18)
==> virtualbox-windows-ovf: Provisioning with windows-shell...
==> virtualbox-windows-ovf: Provisioning with shell script: ./scripts/testenvvars.ps1
==> virtualbox-windows-ovf: Uploading ./DSC => C:/Windows/Temp/DSC
Build 'virtualbox-windows-ovf' errored: unexpected EOF

==> Some builds didn't complete successfully and had errors:
panic: runtime error: slice bounds out of range
2015/01/06 21:37:20 packer-builder-virtualbox-windows-ovf:
2015/01/06 21:37:20 packer-builder-virtualbox-windows-ovf: goroutine 31 [running]:
2015/01/06 21:37:20 packer-builder-virtualbox-windows-ovf: github.com/packer-community/winrmcp/winrmcp.(*fileWalker).copyFile(0xc2081202d0, 0xc20815cb50, 0xe, 0x861ce8, 0xc2081447d0, 0x0, 0x0, 0x0, 0x0)
2015/01/06 21:37:20 packer-builder-virtualbox-windows-ovf: 	/Users/mfellows/go/src/github.com/packer-community/winrmcp/winrmcp/winrmcp.go:72 +0x5d4
2015/01/06 21:37:20 packer-builder-virtualbox-windows-ovf: github.com/packer-community/winrmcp/winrmcp.*fileWalker.(github.com/packer-community/winrmcp/winrmcp.copyFile)·fm(0xc20815cb50, 0xe, 0x861ce8, 0xc2081447d0, 0x0, 0x0, 0x0, 0x0)
2015/01/06 21:37:20 packer-builder-virtualbox-windows-ovf: 	/Users/mfellows/go/src/github.com/packer-community/winrmcp/winrmcp/winrmcp.go:45 +0x7b
2015/01/06 21:37:20 packer-builder-virtualbox-windows-ovf: path/filepath.walk(0xc20815cb50, 0xe, 0x861ce8, 0xc2081447d0, 0xc2081d7958, 0x0, 0x0)
2015/01/06 21:37:20 packer-builder-virtualbox-windows-ovf: 	/opt/boxen/homebrew/Cellar/go/1.4/libexec/src/path/filepath/path.go:347 +0x91
2015/01/06 21:37:20 packer-builder-virtualbox-windows-ovf: path/filepath.walk(0xc20819f095, 0x5, 0x861ce8, 0xc208258dc0, 0xc2081d7958, 0x0, 0x0)
2015/01/06 21:37:20 packer-builder-virtualbox-windows-ovf: 	/opt/boxen/homebrew/Cellar/go/1.4/libexec/src/path/filepath/path.go:372 +0x51d
2015/01/06 21:37:20 packer-builder-virtualbox-windows-ovf: path/filepath.Walk(0xc20819f095, 0x5, 0xc2081d7958, 0x0, 0x0)
2015/01/06 21:37:20 packer-builder-virtualbox-windows-ovf: 	/opt/boxen/homebrew/Cellar/go/1.4/libexec/src/path/filepath/path.go:394 +0xf2
2015/01/06 21:37:20 packer-builder-virtualbox-windows-ovf: github.com/packer-community/winrmcp/winrmcp.(*Winrmcp).Copy(0xc2080a4238, 0xc20819f095, 0x5, 0xc2081a1060, 0x13, 0x0, 0x0)
2015/01/06 21:37:20 packer-builder-virtualbox-windows-ovf: 	/Users/mfellows/go/src/github.com/packer-community/winrmcp/winrmcp/winrmcp.go:45 +0x790
2015/01/06 21:37:20 packer-builder-virtualbox-windows-ovf: github.com/packer-community/packer-windows-plugins/communicator/winrm.(*Communicator).UploadDir(0xc20817a140, 0xc2081a1060, 0x13, 0xc20819f095, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0)
2015/01/06 21:37:20 packer-builder-virtualbox-windows-ovf: 	/Users/mfellows/go/src/github.com/packer-community/packer-windows-plugins/communicator/winrm/communicator.go:120 +0xa9
2015/01/06 21:37:20 packer-builder-virtualbox-windows-ovf: github.com/mitchellh/packer/packer/rpc.(*CommunicatorServer).UploadDir(0xc2081a1020, 0xc208105fc0, 0xc20819f0a0, 0x0, 0x0)
2015/01/06 21:37:20 packer-builder-virtualbox-windows-ovf: 	/Users/mfellows/go/src/github.com/mitchellh/packer/packer/rpc/communicator.go:242 +0x9a
2015/01/06 21:37:20 packer-builder-virtualbox-windows-ovf: reflect.Value.call(0x428520, 0x49c230, 0x13, 0x4f17d0, 0x4, 0xc2081d7f28, 0x3, 0x3, 0x0, 0x0, ...)
2015/01/06 21:37:20 packer-builder-virtualbox-windows-ovf: 	/opt/boxen/homebrew/Cellar/go/1.4/libexec/src/reflect/value.go:419 +0x10e5
2015/01/06 21:37:20 packer-builder-virtualbox-windows-ovf: reflect.Value.Call(0x428520, 0x49c230, 0x13, 0xc2081d7f28, 0x3, 0x3, 0x0, 0x0, 0x0)
2015/01/06 21:37:20 packer-builder-virtualbox-windows-ovf: 	/opt/boxen/homebrew/Cellar/go/1.4/libexec/src/reflect/value.go:296 +0xbc
2015/01/06 21:37:20 packer-builder-virtualbox-windows-ovf: net/rpc.(*service).call(0xc2081b8dc0, 0xc2081b8d80, 0xc2080f1808, 0xc208030780, 0xc208103b80, 0x380540, 0xc208105fc0, 0x16, 0x37e140, 0xc20819f0a0, ...)
2015/01/06 21:37:20 packer-builder-virtualbox-windows-ovf: 	/opt/boxen/homebrew/Cellar/go/1.4/libexec/src/net/rpc/server.go:382 +0x1f7
2015/01/06 21:37:20 packer-builder-virtualbox-windows-ovf: created by net/rpc.(*Server).ServeCodec
2015/01/06 21:37:20 packer-builder-virtualbox-windows-ovf: 	/opt/boxen/homebrew/Cellar/go/1.4/libexec/src/net/rpc/server.go:476 +0x44a
```

**Comment by mefellows** [comment]
Investigation notes: I believe this is linked to https://github.com/packer-community/winrmcp/issues/2

**Comment by mefellows** [comment]
Fixed by addressing the upstream issue in [winrmcp](https://github.com/packer-community/winrmcp/commit/258a16ef8ee9b931bc1f0b51e388cb8ca962b299). Tested packer run with following configuration with no Kernal panic (and correct upload semantics):

```
...
provisioners: [
{
  "type": "file",
  "source": "./DSC",
  "destination": "C:/Windows/Temp/DSC"
},
{
  "type": "file",
  "source": "/Users/mfellows/development/dius/hackathong3-packer/DSC",
  "destination": "C:/Windows/Temp/DSC2"
}
...
```
